@base_adress = http://localhost:3000/api/auth/Register

POST {{base_adress}}
Content-Type: application/json

{
  "Fname" : "Asanda",
  "Lname" : "Ngcobo",
  "Password" : "S78hggf12",
  "Email" : "decoythingpholoba@gmail.com"
}

